### ISSUE TITLE
Update iconv dep to 2.2.0

### ISSUE THREAD

**Issue by jck** [martynsmith/node-irc#463]
The current version of the iconv dependency fails to build on Archlinux.

**Comment by vBm** [comment]
Do tell us which node you're using what's the exact problem (logs).
"Fails to build" means almost nothing since it's too generic.

**Comment by jck** [comment]
I'm using node v6.

iconv@2.1.11 fails to install due to these errors:
```
In file included from ../node-icu-charset-detector.cpp:2:0:
../../nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
node-icu-charset-detector.target.mk:86: recipe for target 'Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o' failed
```

However, iconv@2.2.0 installs without any errors.

Do you need any more information?

**Comment by ellisgl** [comment]
CentOS 7.x - Node 6 - same thing.

**Comment by Ernesto-Paz** [comment]
Just chiming in to say that it works fine for me on OS X 10.10.5.

**Comment by johnkernke** [comment]
+1

Debian 7.10 with node v6.2.0 fails to rebuild with iconv 2.1.11, but 2.2.0 works fine

**Comment by BeckZero** [comment]
+1 windows 10 T.T

**Comment by colwem** [comment]
+1 OSX v10.11.5 node v6.3.1

**Comment by mickae1** [comment]
Same problem on Windows 10 and the last version of nodejs

**Comment by BeauBouchard** [comment]
+1 OSX v10.11.5 node v6.6

**Comment by duanejeffers** [comment]
+1 Ubuntu 16.10 - node v6.8.1

**Comment by Tsarpf** [comment]
+1 Ubuntu 16.04

**Comment by paladox** [comment]
Done in https://github.com/martynsmith/node-irc/commit/ab712043e4247efad168edc2641bc59de10fae99

And released as 0.5.2
